version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:30"
  open-pull-requests-limit: 5
- package-ecosystem: npm
  directory: "/HaloAchievementTracker.WebApp.Client"
  schedule:
    interval: daily
    time: "04:30"
  ignore:
  - dependency-name: "@types/node"
    versions: [15.*]
  - dependency-name: "@angular/*"
  open-pull-requests-limit: 5
