version: 2
updates:
- package-ecosystem: npm
  directory: "/HaloAchievementTracker.WebApp/ClientApp"
  schedule:
    interval: daily
    time: "04:30"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:30"
  open-pull-requests-limit: 10
