language: csharp
os: linux
dist: xenial
mono: none
dotnet: 3.1
env:
  matrix:
  - NODE_VERSION=12.19.0
  - NODE_VERSION=14.15.0
  - NODE_VERSION=15.1.0
before_install:
  - dotnet restore
  - nvm install ${NODE_VERSION}
  - npm install -g @angular/cli
script:
  # Build API
  - cd HaloAchievementTracker.WebApp.API
  - dotnet build
  - dotnet test
  - cd ../
  
  # Build Client
  - cd HaloAchievementTracker.WebApp.Client
  - npm install
  - npm run-script build
  - npm run-script lint
  - cd ../
