language: csharp
os: linux
dist: xenial
mono: none
dotnet: 3.1
before_install:
  - dotnet restore
  - nvm install 12.18.3
  - npm install -g @angular/cli
install:
  - dotnet build
  - pushd HaloAchievementTracker.WebApp/ClientApp && npm run-script build && popd
script:
  - dotnet test
  - pushd HaloAchievementTracker.WebApp/ClientApp && npm run-script lint && popd
