language: csharp
os: linux
dist: xenial
mono: none
dotnet: 3.1
install:
  - dotnet restore
before_script:
  - nvm install 12.18.3
  - nvm use 12.18.3
  - npm install -g @angular/cli
script:
  - dotnet build
  - dotnet test
  - pushd HaloAchievementTracker.WebApp/ClientApp && ng lint && popd
  - pushd HaloAchievementTracker.WebApp/ClientApp && ng build && popd
