language: csharp
os: linux
dist: xenial
mono: none
dotnet: 5.0.100
env:
  matrix:
  - NODE_VERSION=12.19.1
  - NODE_VERSION=14.15.1
before_install:
  - dotnet restore
  - nvm install ${NODE_VERSION}
  - npm install @angular/cli
script:
  # Build VS solution
  - dotnet build
  - dotnet test
  
  # Build Angular client
  - cd HaloAchievementTracker.WebApp.Client
  - npm install
  - npm run-script build:prod
  - npm run-script lint
  - cd ../
