language: csharp
os: linux
dist: xenial
mono: none
dotnet: 3.1
before_install:
  - dotnet restore
  - nvm install 14.15.0
  - npm install -g @angular/cli
script:
  # Build API
  - cd HaloAchievementTracker.WebApp.API
  - dotnet build
  - dotnet test
  - cd ../
  
  # Build Client
  - cd HaloAchievementTracker.WebApp.Client
  - npm install
  - npm run-script build
  - npm run-script lint
  - cd ../
