yarnPath: '.yarn/releases/yarn-berry.cjs'
nodeLinker: node-modules
packageExtensions:
  '@angular-eslint/schematics@12.1.0':
    peerDependencies:
      '@angular/compiler': '12.0.3'
      'eslint': '7.27.0'
      'typescript': '4.2.4'
logFilters:
  - code: YN0062
    level: discard
