yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
logFilters:
  - text: "@angular-eslint/schematics@npm:2.0.0 [1028e] doesn't provide @angular-eslint/template-parser (p48bf6), requested by @angular-eslint/eslint-plugin-template"
    level: discard
  - code: "YN0002"
    level: error
  - code: "YN0059"
    level: error
  - code: "YN0060"
    level: error
  - code: "YN0062"
    level: discard
